version: "3.8"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/home/alxgav/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123qwerty
      - POSTGRES_DB=raving_db
      - POSTGRES_HOST=127.0.0.1
volumes:
  postgres_data:
